### ISSUE TITLE
link for fast scnn fp

### ISSUE THREAD

**Issue by concrete13377** [hukenovs/easyportrait#20]
links for fastscnn-ps and fastscnn-fp is the same (sp) 
![image](https://github.com/hukenovs/easyportrait/assets/32034827/5250f076-8afb-449c-b065-2d5795faa888)
![image](https://github.com/hukenovs/easyportrait/assets/32034827/d8a7d34a-927f-482e-95bd-30db49860a5b)

same for EHANet

**Comment by befozg** [comment]
@concrete13377 Hi! Updated missing links, please try again.
