### ISSUE TITLE
[Question] Inquiry regarding image sources in the dataset

### ISSUE THREAD

**Issue by mmoyano-sigmacognition** [hukenovs/easyportrait#32]
Hi,

First of all, thanks for your work and for releasing the dataset for commercial use. I've read the paper, specifically the " Image Collection & Labeling" section, but I was wondering if there’s a possibility that some of the images might have been sourced from the Internet.

Thank you for your time. Cheers,
Manuel

**Comment by hukenovs** [comment]
Hello!

We tried to collect images of real people from crowdsourcing platforms. Unscrupulous workers could upload a random photo that passed the validation stage even with the overlap of 3-5. 

Thanks!
Alexander

**Comment by mmoyano-sigmacognition** [comment]
Hi!!

Thanks for the quick response @hukenovs 😊. Doubt resolved, so I close the issue.

Greetings,
Manuel
