### ISSUE TITLE
How to color the nostrils and white part of eyes also?

### ISSUE THREAD

**Issue by arnold408** [hukenovs/easyportrait#7]
How to color the nostrils and white part of eyes also?

**Comment by gofixyourself** [comment]
Hi! 

Thank you for asking. Unfortunately, the EasyPortrait dataset doesn't incorporate classes designated as "nostrils" or "white of the eye." The "white of the eye" is recognized as a part of the "left eye" or "right eye" classes. And nostrils are considered just not a part of the facial skin class.

**Comment by gofixyourself** [comment]
I was thinking of a solution that might help you out. Using OpenCV's [findContours](https://docs.opencv.org/3.4/d4/d73/tutorial_py_contours_begin.html), you can locate the nostrils and whites of the eyes and then fill them with black. I hope this idea works for you!

**Comment by emlcpfx** [comment]
Where is the color palette located?
