### ISSUE TITLE
about   assert palette.shape[0] == len(self.CLASSES)   error ?

### ISSUE THREAD

**Issue by zhanghongyong123456** [hukenovs/easyportrait#8]
![image](https://github.com/hukenovs/easyportrait/assets/48466610/bf3e70be-a17a-486a-b14c-c8107bf3e7c6)

my  config set:
![image](https://github.com/hukenovs/easyportrait/assets/48466610/077a4e01-70e4-4f81-8315-24d04177f8ff)

**Comment by zhanghongyong123456** [comment]
Ask a face alignment question:
I have an image（1920x1080 size） which contains  faces, 
 Step 1: Detect faces（size 1024x1024）
Step 2: Face Alignment
Step 3: Operate the face to get the processed face
Step 4: put the processed face back to the original position of the original image
about Step4 ，How to restore the face alignment operation in the second step

**Comment by gofixyourself** [comment]
Thank you for reaching out! 

To help you solve the first problem, please set --palette=easy_portrait in your run configurations. Check the inference code example [here](https://github.com/hukenovs/easyportrait/blob/main/pipelines/demo/image_demo.py).
